import { ImageInfo, Tag } from './types';

const [
  sunset,
  sunrise,
  beach,
  ocean,
  mountain,
  snow,
  lake,
  flowers,
  macro,
  wildlife,
  yosemite,
  structures,
  international,
  perspective,
  waterfall,
  natPark,
  fall,
] = [
  Tag.Sunset,
  Tag.Sunrise,
  Tag.Beach,
  Tag.Ocean,
  Tag.Mountain,
  Tag.Snow,
  Tag.Lake,
  Tag.Flowers,
  Tag.Macro,
  Tag.Wildlife,
  Tag.Yosemite,
  Tag.Structures,
  Tag.International,
  Tag.Perspective,
  Tag.Waterfall,
  Tag.NationalPark,
  Tag.Fall,
];

const info: ImageInfo = {
  '0054': { tags: [flowers, macro] },
  '0096': { tags: [flowers, macro] },
  '0266': { tags: [flowers, macro] },
  '0357': { tags: [lake, sunset, snow, mountain, wildlife] },
  '0481': { tags: [mountain, yosemite] },
  '0613': { tags: [yosemite, mountain, sunset, natPark] },
  '0691': { tags: [yosemite, macro, perspective, natPark, fall] },
  '0739': { tags: [waterfall, yosemite, perspective, natPark] },
  '0816': { tags: [sunset, lake] },
  '0902': { tags: [perspective] },
  '0906': { tags: [sunset, perspective] },
  '0961': { tags: [sunset, lake] },
  '0963': { tags: [sunset] },
  '1022': { tags: [sunset, lake] },
  '1083': { tags: [perspective, natPark] },
  '1161': { tags: [sunset, lake, natPark] },
  '1205': { tags: [sunset, lake, natPark] },
  '1245': { tags: [sunset, lake, natPark] },
  '1318': { tags: [sunrise, natPark] },
  '1538': { tags: [lake, fall] },
  '1964': { tags: [mountain, sunset, yosemite, natPark] },
  '2109': { tags: [mountain, sunrise, yosemite, natPark] },
  '2191': { tags: [sunset] },
  '2634': { tags: [sunset, mountain] },
  '3043': { tags: [snow] },
  '3066': { tags: [lake, perspective, sunset] },
  '3101': { tags: [ocean, beach, sunset] },
  '3149': { tags: [sunset, mountain] },
  '3204': { tags: [wildlife, natPark] },
  '3214': { tags: [perspective, natPark] },
  '3299': { tags: [waterfall, yosemite, natPark] },
  '3373': { tags: [mountain] },
  '3387': { tags: [perspective, lake, sunset] },
  '3415': { tags: [perspective, mountain] },
  '3430': { tags: [mountain] },
  '3530': { tags: [ocean, international] },
  '3533': { tags: [beach, ocean, international, perspective, wildlife] },
  '3599': { tags: [international, ocean, beach] },
  '3761': { tags: [structures, perspective, international] },
  '3800': { tags: [wildlife, international] },
  '3851': { tags: [international, mountain] },
  '4002': { tags: [international, structures] },
  '4016': { tags: [flowers, international, perspective] },
  '4044': { tags: [international, structures] },
  '4074': { tags: [international, structures, perspective] },
  '4106': { tags: [international, structures] },
  '4162': { tags: [international, structures, perspective] },
  '4196': { tags: [mountain] },
  '4349': { tags: [beach, perspective] },
  '4365': { tags: [beach, perspective] },
  '4368': { tags: [beach, ocean] },
  '4418': { tags: [beach, sunset, ocean, perspective] },
  '4452': { tags: [beach, sunset, perspective] },
  '4470': { tags: [beach, perspective] },
  '4561': { tags: [mountain] },
  '4597': { tags: [international, structures, perspective] },
  '4643': { tags: [perspective, mountain, international] },
  '4700': { tags: [perspective, international] },
  '4751': { tags: [international, mountain, snow] },
  '5066': { tags: [international, lake, mountain] },
  '5096': { tags: [international, mountain] },
  '5124': { tags: [international, ocean, waterfall, perspective] },
  '5169': { tags: [international, mountain] },
  '5252': { tags: [international, mountain] },
  '5264': { tags: [international, mountain] },
  '5307': { tags: [international, mountain, lake] },
  '5377': { tags: [international, lake, snow, mountain, perspective] },
  '5455': { tags: [international, mountain, lake, sunset] },
  '5461': { tags: [international, mountain, sunset] },
  '5696': { tags: [flowers, macro] },
  '5710': { tags: [international, perspective] },
  '5757': { tags: [macro, wildlife, international] },
  '5866': { tags: [perspective, international, structures] },
  '6123': { tags: [natPark, international] },
  '6240': { tags: [structures, perspective] },
  '6259': { tags: [structures, perspective] },
  '6428': { tags: [natPark, yosemite, perspective] },
  '6549': { tags: [natPark, yosemite, waterfall, mountain] },
  '6630': { tags: [mountain] },
  '6650': { tags: [mountain] },
  '6681': { tags: [mountain, sunset] },
  '6786': { tags: [mountain, sunset, flowers] },
  '6892': { tags: [mountain, flowers] },
  '7235': { tags: [international, perspective] },
  '7297': { tags: [international, perspective, waterfall] },
  '7363': { tags: [ocean, beach] },
  '7378': { tags: [snow, perspective, natPark, yosemite] },
  '7490': { tags: [international, structures] },
  '7494': { tags: [international, structures, perspective] },
  '7546': { tags: [international, ocean, structures] },
  '7585': { tags: [international, ocean] },
  '7673': { tags: [international, perspective] },
  '7726': { tags: [sunset, mountain] },
  '7742': { tags: [lake, natPark, yosemite, mountain] },
  '7844': { tags: [natPark, yosemite] },
  '7895': { tags: [lake, mountain] },
  '7911': { tags: [lake, mountain] },
  '7941': { tags: [mountain] },
  '7968': { tags: [mountain, fall] },
  '7971': { tags: [fall, perspective] },
  '8174': { tags: [waterfall, perspective, fall] },
  '8185': { tags: [fall, waterfall] },
  '8294': { tags: [natPark, fall] },
  '8309': { tags: [fall, natPark] },
  '8345': { tags: [fall, natPark] },
  '8450': { tags: [sunrise, ocean, beach, natPark] },
  '8485': { tags: [sunrise, ocean, beach, natPark] },
  '8596': { tags: [natPark, mountain, yosemite] },
  '8653': { tags: [mountain] },
  '8665': { tags: [mountain] },
  '8944': { tags: [sunset, natPark, mountain] },
  '9016': { tags: [mountain, natPark] },
  '9042': { tags: [mountain, natPark] },
  '9102': { tags: [sunset, natPark, mountain] },
  '9167': { tags: [snow] },
  '9180': { tags: [mountain, waterfall] },
  '9205': { tags: [mountain, snow] },
  '9293': { tags: [flowers, macro] },
  '9316': { tags: [waterfall, natPark, yosemite, perspective] },
  '9339': { tags: [mountain, natPark, yosemite, perspective] },
  '9581': { tags: [mountain, natPark] },
  '9754': { tags: [mountain, natPark] },
  '10045': { tags: [mountain, flowers] },
};

export default info;
